spring:
  rabbitmq:
    host: 192.168.2.9
    port: 5672
    username: yh
    password: yh
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual